### ISSUE TITLE
IRC Network cannot be edited if no channels exist

### ISSUE THREAD

**Issue by SavageCore** [autobrr/autobrr#158]
Upon clicking on an IRC network with no channels you receive the error:

```
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'length')
    at children (IrcForms.tsx:25:52)
    at n.r.render (FieldArray.tsx:367:12)
    at Qi (react-dom.production.min.js:187:188)
    at Wi (react-dom.production.min.js:186:173)
    at Zs (react-dom.production.min.js:269:427)
    at Pl (react-dom.production.min.js:250:347)
    at Rl (react-dom.production.min.js:250:278)
    at Nl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
cs @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
ho @ react-dom.production.min.js:131
gs @ react-dom.production.min.js:220
Al @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Qa @ react-dom.production.min.js:122
Il @ react-dom.production.min.js:252
bl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Qa @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
Ll @ react-dom.production.min.js:263
t.unstable_runWithPriority @ scheduler.production.min.js:18
Qa @ react-dom.production.min.js:122
Fl @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
D @ scheduler.production.min.js:16
x.port1.onmessage @ scheduler.production.min.js:12
IrcForms.tsx:25 Uncaught TypeError: Cannot read properties of null (reading 'length')
    at children (IrcForms.tsx:25:52)
    at n.r.render (FieldArray.tsx:367:12)
    at Qi (react-dom.production.min.js:187:188)
    at Wi (react-dom.production.min.js:186:173)
    at Zs (react-dom.production.min.js:269:427)
    at Pl (react-dom.production.min.js:250:347)
    at Rl (react-dom.production.min.js:250:278)
    at Nl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
children @ IrcForms.tsx:25
r.render @ FieldArray.tsx:367
Qi @ react-dom.production.min.js:187
Wi @ react-dom.production.min.js:186
Zs @ react-dom.production.min.js:269
Pl @ react-dom.production.min.js:250
Rl @ react-dom.production.min.js:250
Nl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Qa @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
Ll @ react-dom.production.min.js:263
t.unstable_runWithPriority @ scheduler.production.min.js:18
Qa @ react-dom.production.min.js:122
Fl @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
D @ scheduler.production.min.js:16
x.port1.onmessage @ scheduler.production.min.js:12
```

Fix is probably as simple as changing [this line](https://github.com/autobrr/autobrr/blob/develop/web/src/forms/settings/IrcForms.tsx#L25) to:

```
 {values && values.channels && values.channels.length > 0 ? (
```

I'm not well versed enough in Go to PR this I'm afraid

**Comment by ludviglundgren** [comment]
Fixed in #159
