### ISSUE TITLE
App crashes when announcement is made

### ISSUE THREAD

**Issue by roughwood** [autobrr/autobrr#554]
**Version**
v1.11.0

**Describe the bug**
While connect to IRC and monitoring, when an announcement is made the app crashes.

**Stack Trace**
```
autobrr  | {"level":"debug","module":"irc","network":"irc.broadcasthe.net","channel":"#btn-announce","user":"Barney","time":"2022-12-02T05:04:35Z","message":"[ https://broadcasthe.net/torrents.php?id=829172 / https://broadcasthe.net/torrents.php?action=download&id=1701063 ]"}
autobrr  | etc.go:805:parseZoneOffset: TODOTODO "\"America/New_York\""
autobrr  | goroutine 136 [running]:
autobrr  | runtime/debug.Stack()
autobrr  |      /usr/local/go/src/runtime/debug/stack.go:24 +0x65
autobrr  | modernc.org/libc.todo({0xec6b9b?, 0x12?}, {0xc000ca7d58?, 0x4550e9?, 0x12?})
autobrr  |      /go/pkg/mod/modernc.org/libc@v1.18.0/etc.go:100 +0x13c
autobrr  | modernc.org/libc.parseZoneOffset({0xc0004cc510?, 0xc0001c9520?}, 0x12?)
autobrr  |      /go/pkg/mod/modernc.org/libc@v1.18.0/etc.go:805 +0x145
autobrr  | modernc.org/libc.parseZone(...)
autobrr  |      /go/pkg/mod/modernc.org/libc@v1.18.0/etc.go:791
autobrr  | modernc.org/libc.Xlocaltime(0x10?, 0x1512a1400598)
autobrr  |      /go/pkg/mod/modernc.org/libc@v1.18.0/libc_linux.go:137 +0x385
autobrr  | modernc.org/sqlite/lib.osLocaltime(0xc000ca7ec0?, 0xa02830?, 0x1512a1400530)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/lib/sqlite_linux_amd64.go:13674 +0x86
autobrr  | modernc.org/sqlite/lib.toLocaltime(0xc000510770, 0x1512a1400470, 0x1512a060aac8)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/lib/sqlite_linux_amd64.go:13725 +0x1de
autobrr  | modernc.org/sqlite/lib.parseModifier(0xc000510770, 0xa359ba?, 0x1512a0608f48, 0x9, 0x1512a1400470, 0x1)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/lib/sqlite_linux_amd64.go:13847 +0x6a5
autobrr  | modernc.org/sqlite/lib.isDate(0xa04efe?, 0x1512a0601df0?, 0x2, 0x1512a060aaf8, 0x1512a1400470)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/lib/sqlite_linux_amd64.go:14136 +0x236
autobrr  | modernc.org/sqlite/lib.datetimeFunc(0xc000510770, 0x1512a040d220?, 0xa1400180?, 0x1512a1400320?)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/lib/sqlite_linux_amd64.go:14190 +0x8f
autobrr  | modernc.org/sqlite/lib.Xsqlite3VdbeExec(0xc000510770, 0x1512a0600e38)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/lib/sqlite_linux_amd64.go:76150 +0xef3c
autobrr  | modernc.org/sqlite/lib.sqlite3Step(0xc0004f0e40?, 0x1512a0600e38)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/lib/sqlite_linux_amd64.go:62524 +0x73
autobrr  | modernc.org/sqlite/lib.Xsqlite3_step(0x1?, 0x1512a0600e38)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/lib/sqlite_linux_amd64.go:62606 +0xae
autobrr  | modernc.org/sqlite.(*conn).step(0xc0004f0e40, 0xbb95c0?)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/sqlite.go:916 +0x3a
autobrr  | modernc.org/sqlite.(*stmt).query.func1(0xc000716850, 0xc000ca87a0, {0xc0006227b0?, 0x8?, 0x1512c934c108?}, 0xc000ca87d8, 0xc000ca87b8, 0xc000ca87a8)
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/sqlite.go:603 +0xc5
autobrr  | modernc.org/sqlite.(*stmt).query(0xc000716850, {0x14e5e70, 0xc00003e048}, {0xc0006227b0, 0x1, 0x1})
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/sqlite.go:644 +0x1c5
autobrr  | modernc.org/sqlite.(*conn).query(0x0?, {0x14e5e70, 0xc00003e048}, {0xf125ef?, 0x0?}, {0xc0006227b0, 0x1, 0x1})
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/sqlite.go:1420 +0x12c
autobrr  | modernc.org/sqlite.(*conn).QueryContext(0x13?, {0x14e5e70?, 0xc00003e048?}, {0xf125ef?, 0x12?}, {0xc0006227b0?, 0x6?, 0xed3423?})
autobrr  |      /go/pkg/mod/modernc.org/sqlite@v1.18.2/sqlite_go18.go:38 +0x2d
autobrr  | database/sql.ctxDriverQuery({0x14e5e70?, 0xc00003e048?}, {0x1512a18524b8?, 0xc0004f0e40?}, {0x0?, 0x0?}, {0xf125ef?, 0xef1066?}, {0xc0006227b0, 0x1, ...})
autobrr  |      /usr/local/go/src/database/sql/ctxutil.go:48 +0xe5
autobrr  | database/sql.(*DB).queryDC.func1()
autobrr  |      /usr/local/go/src/database/sql/sql.go:1757 +0x175
autobrr  | database/sql.withLock({0x14e2578, 0xc0000ce360}, 0xc000ca8b88)
autobrr  |      /usr/local/go/src/database/sql/sql.go:3439 +0x8c
autobrr  | database/sql.(*DB).queryDC(0xe11b40?, {0x14e5e70, 0xc00003e048}, {0x14e5e38, 0xc0001d1240}, 0xc0000ce360, 0xc000716840, {0xf125ef, 0x27b}, {0xc000ca8ce8, ...})
autobrr  |      /usr/local/go/src/database/sql/sql.go:1752 +0x211
autobrr  | database/sql.(*Tx).QueryContext(0xc0001c6d80, {0x14e5e70, 0xc00003e048}, {0xf125ef, 0x27b}, {0xc000ca8ce8, 0x1, 0x1})
autobrr  |      /usr/local/go/src/database/sql/sql.go:2510 +0xcf
autobrr  | database/sql.(*Tx).QueryRowContext(...)
autobrr  |      /usr/local/go/src/database/sql/sql.go:2528
autobrr  | github.com/autobrr/autobrr/internal/database.(*FilterRepo).downloadsByFilterSqlite(0xc000510930, {0x14e5e70, 0xc00003e048}, 0xc0007596b8?, 0xc000ca85f8?)
autobrr  |      /src/internal/database/filter.go:1026 +0x9e
autobrr  | github.com/autobrr/autobrr/internal/database.(*FilterRepo).attachDownloadsByFilter(0xc000168dd0?, {0x14e5e70?, 0xc00003e048?}, 0xc0001bff60?, 0xc000c800a0?)
autobrr  |      /src/internal/database/filter.go:1010 +0x4a
autobrr  | github.com/autobrr/autobrr/internal/database.(*FilterRepo).FindByIndexerIdentifier(0xc000510930, {0xc000c800a0, 0x3})
autobrr  |      /src/internal/database/filter.go:316 +0x2ca
autobrr  | github.com/autobrr/autobrr/internal/filter.(*service).FindByIndexerIdentifier(0xc00089c5a0, {0xc000c800a0, 0x3})
autobrr  |      /src/internal/filter/service.go:129 +0x38
autobrr  | github.com/autobrr/autobrr/internal/release.(*service).Process(0xc0000ce990, 0xc0003d8000)
autobrr  |      /src/internal/release/service.go:94 +0x64
autobrr  | created by github.com/autobrr/autobrr/internal/announce.(*announceProcessor).processQueue
autobrr  |      /src/internal/announce/announce.go:111 +0x21b
autobrr  |

```

This is running under Docker

**Comment by zze0s** [comment]
Interesting :thinking: Are you using docker run or a compose file? How do you set the timezone?

**Comment by roughwood** [comment]
This is using Docker Compose. Everything was working great until ~9 days ago. I don't recall if that coincided with me updating the container or anything, though.

```
version: "3.7"

services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: "no"
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ="America/New_York"
    volumes:
      - ./config:/config
    ports:
      - 7576:7474
```

**Comment by zze0s** [comment]
We did do some changes related to loading timezone etc with 1.10.0 or 1.11.0 so that might explain parts of it.

Can you try remove the quotes around TZ like `TZ=America/New_York` and see if that makes a difference?

**Comment by roughwood** [comment]
It looks like removing the quotes does fix the issue. Thank you!

**Comment by zze0s** [comment]
Great!! This line `etc.go:805:parseZoneOffset: TODOTODO "\"America/New_York\""` was the hint with the escaped double quote, and it [hit's this default case in the SQLite driver](https://gitlab.com/cznic/libc/-/blob/master/etc.go#L805-808). Good to remember if someone else ever run into this again :smile:
